#----------------------------------------------------------------------------
#       Make Workspace
#
# $Id: MakeWorkspaceCreator.pm 2191 2014-03-05 22:06:46Z mitza $
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# ../MPC/mwc.pl -type make -value_template "configurations=Debug Release" -value_template "compilerflags=-std=c++1y -Wall" -value_template "platforms=linux mingw" -value_template mingw::delete=del
#
#----------------------------------------------------------------------------


all: Sett2015

depend: Sett2015-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.Sett2015 $(@)

.PHONY: Sett2015
Sett2015:
	@$(MAKE) -f Makefile.Sett2015 all

.PHONY: Sett2015-depend
Sett2015-depend:
	@$(MAKE) -f Makefile.Sett2015 depend

project_name_list:
	@echo Sett2015
